//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD:ProjectGroenBos/Recreatie/test.aspx.designer.cs
namespace ProjectGroenBos.Recreatie
{


    public partial class test
=======
namespace ProjectGroenBos.Schoonmaak_en_Onderhoud
{


    public partial class Home
>>>>>>> ReserveringTeam/Noah:ProjectGroenBos/Schoonmaak en Onderhoud/Home.aspx.designer.cs
    {
    }
}
